-- =============================================================
-- Cursed-item passives: the custom class spells of mod-custom-spells
-- GENERATED by tools/gen_class_passives.py from the picker manifest
-- (mod-custom-spells/data/spellbook_enUS.json) - edit the manifest or the
-- tool, never this file. Enchantment ids are frozen in
-- data/class_passive_enchants.json (items keep the id they rolled).
-- 218 spells, enchantments 950007-950224, weight 10 per spec (the stat passives
-- of paragon_passive_spells.sql weigh 100). Not in the pool: 900534 active (Barrage, a channel), 900713 active (Targeted Blink), 900741 active (Meteor), 900771 active (Comet Shower).
-- =============================================================

-- Effect_1 3 = ITEM_ENCHANTMENT_TYPE_EQUIP_SPELL: the item casts EffectArg_1 on equip
DELETE FROM `spellitemenchantment_dbc` WHERE `ID` BETWEEN 950007 AND 950224;
INSERT INTO `spellitemenchantment_dbc` (`ID`, `Charges`, `Effect_1`, `Effect_2`, `Effect_3`, `EffectPointsMin_1`, `EffectPointsMin_2`, `EffectPointsMin_3`, `EffectPointsMax_1`, `EffectPointsMax_2`, `EffectPointsMax_3`, `EffectArg_1`, `EffectArg_2`, `EffectArg_3`, `Name_Lang_enUS`, `ItemVisual`, `Flags`, `Src_ItemID`, `Condition_Id`, `RequiredSkillID`, `RequiredSkillRank`, `MinLevel`) VALUES
(950007, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900100, 0, 0, 'Passive: Mortal Strike: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950008, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900101, 0, 0, 'Passive: Mortal Strike: -2 sec Cooldown', 0, 0, 0, 0, 0, 0, 0),
(950009, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900102, 0, 0, 'Passive: Overpower: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950010, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900103, 0, 0, 'Passive: Mortal Strike: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950011, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900104, 0, 0, 'Passive: Overpower: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950012, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900105, 0, 0, 'Passive: Critical Execution', 0, 0, 0, 0, 0, 0, 0),
(950013, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900107, 0, 0, 'Passive: Timed Attacks', 0, 0, 0, 0, 0, 0, 0),
(950014, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900108, 0, 0, 'Passive: Whirlwind: Unlimited Targets', 0, 0, 0, 0, 0, 0, 0),
(950015, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900109, 0, 0, 'Passive: Bloodthirst: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950016, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900110, 0, 0, 'Passive: Bloodthirst: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950017, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900111, 0, 0, 'Passive: Whirlwind: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950018, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900112, 0, 0, 'Passive: Cleave: Unlimited Targets', 0, 0, 0, 0, 0, 0, 0),
(950019, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900114, 0, 0, 'Passive: Whirly Attacks', 0, 0, 0, 0, 0, 0, 0),
(950020, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900116, 0, 0, 'Passive: Bloody Whirlwind', 0, 0, 0, 0, 0, 0, 0),
(950021, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900117, 0, 0, 'Passive: Speedy Bloodthirst', 0, 0, 0, 0, 0, 0, 0),
(950022, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900118, 0, 0, 'Passive: Whirlwind: Overpower', 0, 0, 0, 0, 0, 0, 0),
(950023, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900119, 0, 0, 'Passive: Whirlwind: Bloodthirst', 0, 0, 0, 0, 0, 0, 0),
(950024, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900168, 0, 0, 'Passive: Revenge: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950025, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900169, 0, 0, 'Passive: Revenge: Sweeping', 0, 0, 0, 0, 0, 0, 0),
(950026, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900170, 0, 0, 'Passive: Thunder Clap: Rend and Sunder', 0, 0, 0, 0, 0, 0, 0),
(950027, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900171, 0, 0, 'Passive: Thunder Clap: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950028, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900172, 0, 0, 'Passive: Devastate Lightning', 0, 0, 0, 0, 0, 0, 0),
(950029, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900173, 0, 0, 'Passive: Block: Enhanced Thunder Clap', 0, 0, 0, 0, 0, 0, 0),
(950030, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900200, 0, 0, 'Passive: Holy Shock: Burst', 0, 0, 0, 0, 0, 0, 0),
(950031, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900201, 0, 0, 'Passive: Holy Shock: Radiance', 0, 0, 0, 0, 0, 0, 0),
(950032, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900202, 0, 0, 'Passive: Holy Shock: Both Ways', 0, 0, 0, 0, 0, 0, 0),
(950033, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900203, 0, 0, 'Passive: Holy Shock: +50% Effect', 0, 0, 0, 0, 0, 0, 0),
(950034, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900204, 0, 0, 'Passive: Consecration: Healing', 0, 0, 0, 0, 0, 0, 0),
(950035, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900205, 0, 0, 'Passive: Consecration: Follows You', 0, 0, 0, 0, 0, 0, 0),
(950036, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900206, 0, 0, 'Passive: Consecration: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950037, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900207, 0, 0, 'Passive: Consecration: +5 sec Duration', 0, 0, 0, 0, 0, 0, 0),
(950038, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900234, 0, 0, 'Passive: Consecration: Follows You', 0, 0, 0, 0, 0, 0, 0),
(950039, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900235, 0, 0, 'Passive: Avenger''s Shield: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950040, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900236, 0, 0, 'Passive: Avenger''s Shield: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950041, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900237, 0, 0, 'Passive: Holy Shield: +99 Charges', 0, 0, 0, 0, 0, 0, 0),
(950042, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900238, 0, 0, 'Passive: Holy Shield: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950043, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900239, 0, 0, 'Passive: Avenger''s Shield: Consecration', 0, 0, 0, 0, 0, 0, 0),
(950044, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900240, 0, 0, 'Passive: Judgement: Avenger''s Shield', 0, 0, 0, 0, 0, 0, 0),
(950045, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900241, 0, 0, 'Passive: Judgement: -2 sec Cooldown', 0, 0, 0, 0, 0, 0, 0),
(950046, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900268, 0, 0, 'Passive: Consecration: Follows You', 0, 0, 0, 0, 0, 0, 0),
(950047, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900269, 0, 0, 'Passive: Judgement: -2 sec Cooldown', 0, 0, 0, 0, 0, 0, 0),
(950048, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900270, 0, 0, 'Passive: Divine Storm: +6 Targets', 0, 0, 0, 0, 0, 0, 0),
(950049, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900271, 0, 0, 'Passive: Divine Storm: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950050, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900272, 0, 0, 'Passive: Crusader Strike: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950051, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900273, 0, 0, 'Passive: Crusader Strike: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950052, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900274, 0, 0, 'Passive: Exorcism Power', 0, 0, 0, 0, 0, 0, 0),
(950053, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900500, 0, 0, 'Passive: Recovered Arrows', 0, 0, 0, 0, 0, 0, 0),
(950054, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900501, 0, 0, 'Passive: Multi-Shot: Unlimited Targets', 0, 0, 0, 0, 0, 0, 0),
(950055, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900502, 0, 0, 'Passive: Pet: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950056, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900503, 0, 0, 'Passive: Pet: +50% Attack Speed', 0, 0, 0, 0, 0, 0, 0),
(950057, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900504, 0, 0, 'Passive: Pet: Beast Cleave', 0, 0, 0, 0, 0, 0, 0),
(950058, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900533, 0, 0, 'Passive: Auto Shot: Ricochet', 0, 0, 0, 0, 0, 0, 0),
(950059, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900566, 0, 0, 'Passive: Explosive Traps', 0, 0, 0, 0, 0, 0, 0),
(950060, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900600, 0, 0, 'Passive: Energy: +50% Regeneration', 0, 0, 0, 0, 0, 0, 0),
(950061, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900601, 0, 0, 'Passive: Mutilate: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950062, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900602, 0, 0, 'Passive: Poisons: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950063, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900603, 0, 0, 'Passive: Poison Nova', 0, 0, 0, 0, 0, 0, 0),
(950064, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900633, 0, 0, 'Passive: Sinister Strike: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950065, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900634, 0, 0, 'Passive: Sinister Strike: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950066, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900635, 0, 0, 'Passive: Blade Flurry: 2 min Duration', 0, 0, 0, 0, 0, 0, 0),
(950067, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900636, 0, 0, 'Passive: Blade Flurry: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950068, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900637, 0, 0, 'Passive: Energy: +50% Regeneration', 0, 0, 0, 0, 0, 0, 0),
(950069, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900666, 0, 0, 'Passive: Energy: +50% Regeneration', 0, 0, 0, 0, 0, 0, 0),
(950070, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900667, 0, 0, 'Passive: Hemorrhage: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950071, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900668, 0, 0, 'Passive: Hemorrhage: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950072, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900900, 0, 0, 'Passive: Power Word: Shield: Explosion', 0, 0, 0, 0, 0, 0, 0),
(950073, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900901, 0, 0, 'Passive: Power Word: Shield: +50% Absorption', 0, 0, 0, 0, 0, 0, 0),
(950074, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900902, 0, 0, 'Passive: Weakened Soul: 5 sec', 0, 0, 0, 0, 0, 0, 0),
(950075, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900933, 0, 0, 'Passive: Holy Fire Heals', 0, 0, 0, 0, 0, 0, 0),
(950076, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900966, 0, 0, 'Passive: Shadow Eruption', 0, 0, 0, 0, 0, 0, 0),
(950077, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900967, 0, 0, 'Passive: Spreading Shadows', 0, 0, 0, 0, 0, 0, 0),
(950078, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900300, 0, 0, 'Passive: Dancing Rune Weapon: Three Blades', 0, 0, 0, 0, 0, 0, 0),
(950079, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900301, 0, 0, 'Passive: Dancing Rune Weapon: Double Cast', 0, 0, 0, 0, 0, 0, 0),
(950080, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900302, 0, 0, 'Passive: Heart Strike: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950081, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900303, 0, 0, 'Passive: Heart Strike: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950082, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900304, 0, 0, 'Passive: Death Coil Strikes', 0, 0, 0, 0, 0, 0, 0),
(950083, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900333, 0, 0, 'Passive: Raise Dead: Frost Wyrm', 0, 0, 0, 0, 0, 0, 0),
(950084, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900366, 0, 0, 'Passive: Plague Eruption', 0, 0, 0, 0, 0, 0, 0),
(950085, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900400, 0, 0, 'Passive: Chain Lightning: +6 Targets', 0, 0, 0, 0, 0, 0, 0),
(950086, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900401, 0, 0, 'Passive: Totems Follow You', 0, 0, 0, 0, 0, 0, 0),
(950087, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900402, 0, 0, 'Passive: Fire Elemental: Ragnaros', 0, 0, 0, 0, 0, 0, 0),
(950088, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900403, 0, 0, 'Passive: Lava Overload', 0, 0, 0, 0, 0, 0, 0),
(950089, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900404, 0, 0, 'Passive: Lava Burst: Spreading Flame', 0, 0, 0, 0, 0, 0, 0),
(950090, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900405, 0, 0, 'Passive: Flame Shock: Lava Reset', 0, 0, 0, 0, 0, 0, 0),
(950091, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900406, 0, 0, 'Passive: Lava Burst: Two Charges', 0, 0, 0, 0, 0, 0, 0),
(950092, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900407, 0, 0, 'Passive: Lava Burst: Clearcast Instant', 0, 0, 0, 0, 0, 0, 0),
(950093, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900433, 0, 0, 'Passive: Totems Follow You', 0, 0, 0, 0, 0, 0, 0),
(950094, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900434, 0, 0, 'Passive: Maelstrom Fury', 0, 0, 0, 0, 0, 0, 0),
(950095, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900435, 0, 0, 'Passive: Empowered Summons', 0, 0, 0, 0, 0, 0, 0),
(950096, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900436, 0, 0, 'Passive: Spirit Wolf Call', 0, 0, 0, 0, 0, 0, 0),
(950097, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900437, 0, 0, 'Passive: Spirit Wolves: Haste', 0, 0, 0, 0, 0, 0, 0),
(950098, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900438, 0, 0, 'Passive: Spirit Wolves: Chain Lightning', 0, 0, 0, 0, 0, 0, 0),
(950099, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900466, 0, 0, 'Passive: Totems Follow You', 0, 0, 0, 0, 0, 0, 0),
(950100, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900467, 0, 0, 'Passive: Deep Reserves', 0, 0, 0, 0, 0, 0, 0),
(950101, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900700, 0, 0, 'Passive: Deep Reserves', 0, 0, 0, 0, 0, 0, 0),
(950102, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900701, 0, 0, 'Passive: Arcane Barrage: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950103, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900702, 0, 0, 'Passive: Arcane Barrage: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950104, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900703, 0, 0, 'Passive: Arcane Blast: -50% Cast Time', 0, 0, 0, 0, 0, 0, 0),
(950105, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900704, 0, 0, 'Passive: Arcane Blast: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950106, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900705, 0, 0, 'Passive: Arcane Blast: 8 Charges', 0, 0, 0, 0, 0, 0, 0),
(950107, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900706, 0, 0, 'Passive: Arcane Explosion: Charges', 0, 0, 0, 0, 0, 0, 0),
(950108, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900707, 0, 0, 'Passive: Evocation Power', 0, 0, 0, 0, 0, 0, 0),
(950109, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900708, 0, 0, 'Passive: Emergency Mana Shield', 0, 0, 0, 0, 0, 0, 0),
(950110, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900709, 0, 0, 'Passive: Blink: To Your Target', 0, 0, 0, 0, 0, 0, 0),
(950111, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900733, 0, 0, 'Passive: Fireball: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950112, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900734, 0, 0, 'Passive: Fireball: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950113, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900735, 0, 0, 'Passive: Pyroblast: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950114, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900736, 0, 0, 'Passive: Pyroblast: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950115, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900737, 0, 0, 'Passive: Fire Blast: Swift and Sure', 0, 0, 0, 0, 0, 0, 0),
(950116, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900738, 0, 0, 'Passive: Pyroblast: Hot Streak', 0, 0, 0, 0, 0, 0, 0),
(950117, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900766, 0, 0, 'Passive: Frostbolt: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950118, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900767, 0, 0, 'Passive: Frostbolt: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950119, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900768, 0, 0, 'Passive: Ice Lance: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950120, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900769, 0, 0, 'Passive: Ice Lance: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950121, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900770, 0, 0, 'Passive: Water Elemental: Permanent', 0, 0, 0, 0, 0, 0, 0),
(950122, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900800, 0, 0, 'Passive: Shadow Eruption', 0, 0, 0, 0, 0, 0, 0),
(950123, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900801, 0, 0, 'Passive: Corruption: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950124, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900802, 0, 0, 'Passive: Spreading Affliction', 0, 0, 0, 0, 0, 0, 0),
(950125, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900833, 0, 0, 'Passive: Metamorphosis: Feast', 0, 0, 0, 0, 0, 0, 0),
(950126, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900834, 0, 0, 'Passive: Metamorphosis: Fel Vigor', 0, 0, 0, 0, 0, 0, 0),
(950127, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900835, 0, 0, 'Passive: Lesser Demons', 0, 0, 0, 0, 0, 0, 0),
(950128, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900836, 0, 0, 'Passive: Imp: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950129, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900837, 0, 0, 'Passive: Imp: Firebolt +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950130, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900838, 0, 0, 'Passive: Felguard: Unlimited Cleave', 0, 0, 0, 0, 0, 0, 0),
(950131, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900839, 0, 0, 'Passive: Felguard: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950132, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900866, 0, 0, 'Passive: Shadow Bolt: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950133, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900867, 0, 0, 'Passive: Shadow Bolt: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950134, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900868, 0, 0, 'Passive: Chaos Bolt: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950135, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900869, 0, 0, 'Passive: Chaos Bolt: -2 sec Cooldown', 0, 0, 0, 0, 0, 0, 0),
(950136, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900870, 0, 0, 'Passive: Chaos Bolt: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950137, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901000, 0, 0, 'Passive: Moonfire: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950138, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901001, 0, 0, 'Passive: Moonfire: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950139, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901002, 0, 0, 'Passive: Starfall: +50% Area', 0, 0, 0, 0, 0, 0, 0),
(950140, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901003, 0, 0, 'Passive: Starfall: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950141, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901004, 0, 0, 'Passive: Starfall: Starlight Reset', 0, 0, 0, 0, 0, 0, 0),
(950142, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901005, 0, 0, 'Passive: Starfall: 10 Stacks', 0, 0, 0, 0, 0, 0, 0),
(950143, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901033, 0, 0, 'Passive: Swipe (Bear): Bleed', 0, 0, 0, 0, 0, 0, 0),
(950144, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901049, 0, 0, 'Passive: Swipe (Cat): Bleed', 0, 0, 0, 0, 0, 0, 0),
(950145, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901051, 0, 0, 'Passive: Energy: +50% Regeneration', 0, 0, 0, 0, 0, 0, 0),
(950146, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901066, 0, 0, 'Passive: Treant Call', 0, 0, 0, 0, 0, 0, 0),
(950147, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901067, 0, 0, 'Passive: Summons: Healing Power', 0, 0, 0, 0, 0, 0, 0),
(950148, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901068, 0, 0, 'Passive: Summons: Parting Bloom', 0, 0, 0, 0, 0, 0, 0),
(950149, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901069, 0, 0, 'Passive: Thorns: Rejuvenation', 0, 0, 0, 0, 0, 0, 0),
(950150, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901070, 0, 0, 'Passive: Heal over Time: +50%', 0, 0, 0, 0, 0, 0, 0),
(950151, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901071, 0, 0, 'Passive: Heal over Time: Double Speed', 0, 0, 0, 0, 0, 0, 0),
(950152, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901072, 0, 0, 'Passive: Deep Reserves', 0, 0, 0, 0, 0, 0, 0),
(950153, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901101, 0, 0, 'Passive: Killing Blow: Recovery', 0, 0, 0, 0, 0, 0, 0),
(950154, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901102, 0, 0, 'Passive: Extra Attack', 0, 0, 0, 0, 0, 0, 0),
(950155, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901103, 0, 0, 'Passive: Cleaving Strikes', 0, 0, 0, 0, 0, 0, 0),
(950156, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901104, 0, 0, 'Passive: Riposte', 0, 0, 0, 0, 0, 0, 0),
(950157, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900133, 0, 0, 'Passive: Whirlwind: Any Stance', 0, 0, 0, 0, 0, 0, 0),
(950158, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901111, 0, 0, 'Passive: Empowered', 0, 0, 0, 0, 0, 0, 0),
(950159, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900306, 0, 0, 'Passive: Bloodworm Burst', 0, 0, 0, 0, 0, 0, 0),
(950160, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900334, 0, 0, 'Passive: Obliterate: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950161, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900335, 0, 0, 'Passive: Obliterate: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950162, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900336, 0, 0, 'Passive: Howling Blast: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950163, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900337, 0, 0, 'Passive: Howling Blast: Frost Fever', 0, 0, 0, 0, 0, 0, 0),
(950164, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900338, 0, 0, 'Passive: Lichborne: Leech', 0, 0, 0, 0, 0, 0, 0),
(950165, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900340, 0, 0, 'Passive: Icy Talons: Frozen Strikes', 0, 0, 0, 0, 0, 0, 0),
(950166, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900369, 0, 0, 'Passive: Ghoul Cleave', 0, 0, 0, 0, 0, 0, 0),
(950167, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900371, 0, 0, 'Passive: Risen Army', 0, 0, 0, 0, 0, 0, 0),
(950168, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900373, 0, 0, 'Passive: Death and Decay: Around You', 0, 0, 0, 0, 0, 0, 0),
(950169, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900410, 0, 0, 'Passive: Lightning Bolt: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950170, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900411, 0, 0, 'Passive: Lightning Bolt: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950171, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900412, 0, 0, 'Passive: Chain Lightning: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950172, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900413, 0, 0, 'Passive: Lava Burst: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950173, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900414, 0, 0, 'Passive: Lava Burst: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950174, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900415, 0, 0, 'Passive: Elemental Resonance', 0, 0, 0, 0, 0, 0, 0),
(950175, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900418, 0, 0, 'Passive: Lightning Shield: Chain Lightning', 0, 0, 0, 0, 0, 0, 0),
(950176, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900714, 0, 0, 'Passive: Arcane Overflow', 0, 0, 0, 0, 0, 0, 0),
(950177, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900715, 0, 0, 'Passive: Mirror Shield', 0, 0, 0, 0, 0, 0, 0),
(950178, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900716, 0, 0, 'Passive: Mirror Images: Splash', 0, 0, 0, 0, 0, 0, 0),
(950179, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901035, 0, 0, 'Passive: Maul: Bleeding Wounds', 0, 0, 0, 0, 0, 0, 0),
(950180, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900507, 0, 0, 'Passive: Pet: +100% Health', 0, 0, 0, 0, 0, 0, 0),
(950181, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900525, 0, 0, 'Passive: Second Pet', 0, 0, 0, 0, 0, 0, 0),
(950182, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900537, 0, 0, 'Passive: Multi-Shot: Serpent Sting', 0, 0, 0, 0, 0, 0, 0),
(950183, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900538, 0, 0, 'Passive: Chimera Shot: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950184, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900539, 0, 0, 'Passive: Chimera Shot: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950185, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900540, 0, 0, 'Passive: Running Aim', 0, 0, 0, 0, 0, 0, 0),
(950186, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900568, 0, 0, 'Passive: Blade and Shot', 0, 0, 0, 0, 0, 0, 0),
(950187, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900571, 0, 0, 'Passive: Raptor Strike: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950188, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900572, 0, 0, 'Passive: Raptor Strike: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950189, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900605, 0, 0, 'Passive: Mutilate: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950190, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900639, 0, 0, 'Passive: Adrenaline Rush: Unleashed', 0, 0, 0, 0, 0, 0, 0),
(950191, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900642, 0, 0, 'Passive: Killing Spree: Fan of Knives', 0, 0, 0, 0, 0, 0, 0),
(950192, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900670, 0, 0, 'Passive: Ambush: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950193, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900671, 0, 0, 'Passive: Ambush: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950194, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900672, 0, 0, 'Passive: Shadow Dance: Flow', 0, 0, 0, 0, 0, 0, 0),
(950195, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900674, 0, 0, 'Passive: Frontal Assault', 0, 0, 0, 0, 0, 0, 0),
(950196, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900904, 0, 0, 'Passive: Atonement', 0, 0, 0, 0, 0, 0, 0),
(950197, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900905, 0, 0, 'Passive: Smite: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950198, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900906, 0, 0, 'Passive: Smite: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950199, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900935, 0, 0, 'Passive: Holy Fire: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950200, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900936, 0, 0, 'Passive: Holy Fire: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950201, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900937, 0, 0, 'Passive: Lightwell: Auto Renew', 0, 0, 0, 0, 0, 0, 0),
(950202, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900938, 0, 0, 'Passive: Spirit of Redemption: Guardian', 0, 0, 0, 0, 0, 0, 0),
(950203, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900941, 0, 0, 'Passive: Holy Nova: +50% Radius', 0, 0, 0, 0, 0, 0, 0),
(950204, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900942, 0, 0, 'Passive: Holy Nova: Kindled Fire', 0, 0, 0, 0, 0, 0, 0),
(950205, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900969, 0, 0, 'Passive: Shadow Word: Pain: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950206, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900970, 0, 0, 'Passive: Mind Blast: +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950207, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900971, 0, 0, 'Passive: Mind Blast: +9 Targets', 0, 0, 0, 0, 0, 0, 0),
(950208, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900972, 0, 0, 'Passive: Shadowform: Soul Feast', 0, 0, 0, 0, 0, 0, 0),
(950209, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900975, 0, 0, 'Passive: Shadowform: Lesser Tentacles', 0, 0, 0, 0, 0, 0, 0),
(950210, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900804, 0, 0, 'Passive: Withering Harvest', 0, 0, 0, 0, 0, 0, 0),
(950211, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900846, 0, 0, 'Passive: Imp: Firebolt 50% Faster', 0, 0, 0, 0, 0, 0, 0),
(950212, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900848, 0, 0, 'Passive: Voidwalker: Void Bulwark', 0, 0, 0, 0, 0, 0, 0),
(950213, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900850, 0, 0, 'Passive: Succubus: Mass Seduction', 0, 0, 0, 0, 0, 0, 0),
(950214, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900852, 0, 0, 'Passive: Felhunter: Area Spell Lock and Devour Magic', 0, 0, 0, 0, 0, 0, 0),
(950215, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900858, 0, 0, 'Passive: Second Demon', 0, 0, 0, 0, 0, 0, 0),
(950216, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900873, 0, 0, 'Passive: Hellfire: Free Movement', 0, 0, 0, 0, 0, 0, 0),
(950217, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 900875, 0, 0, 'Passive: Rain of Fire: Around You', 0, 0, 0, 0, 0, 0, 0),
(950218, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901006, 0, 0, 'Passive: Lunar Frenzy', 0, 0, 0, 0, 0, 0, 0),
(950219, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901036, 0, 0, 'Passive: Swipe (Bear): +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950220, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901037, 0, 0, 'Passive: Thorns: Open Wounds', 0, 0, 0, 0, 0, 0, 0),
(950221, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901039, 0, 0, 'Passive: Ursine Bulwark', 0, 0, 0, 0, 0, 0, 0),
(950222, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901052, 0, 0, 'Passive: Swipe (Cat): +50% Damage', 0, 0, 0, 0, 0, 0, 0),
(950223, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901053, 0, 0, 'Passive: Frontal Assault', 0, 0, 0, 0, 0, 0, 0),
(950224, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 901054, 0, 0, 'Passive: Berserk: Unleashed', 0, 0, 0, 0, 0, 0, 0);

DELETE FROM `paragon_passive_spell_pool` WHERE `enchantmentId` BETWEEN 950007 AND 950224;
INSERT INTO `paragon_passive_spell_pool` (`enchantmentId`, `spellId`, `name`, `category`, `minParagonLevel`, `minItemLevel`) VALUES
(950007, 900100, 'Mortal Strike: +50% Damage', 0, 1, 0),
(950008, 900101, 'Mortal Strike: -2 sec Cooldown', 0, 1, 0),
(950009, 900102, 'Overpower: +50% Damage', 0, 1, 0),
(950010, 900103, 'Mortal Strike: +9 Targets', 0, 1, 0),
(950011, 900104, 'Overpower: +9 Targets', 0, 1, 0),
(950012, 900105, 'Critical Execution', 0, 1, 0),
(950013, 900107, 'Timed Attacks', 0, 1, 0),
(950014, 900108, 'Whirlwind: Unlimited Targets', 0, 1, 0),
(950015, 900109, 'Bloodthirst: +50% Damage', 0, 1, 0),
(950016, 900110, 'Bloodthirst: +9 Targets', 0, 1, 0),
(950017, 900111, 'Whirlwind: +50% Damage', 0, 1, 0),
(950018, 900112, 'Cleave: Unlimited Targets', 0, 1, 0),
(950019, 900114, 'Whirly Attacks', 0, 1, 0),
(950020, 900116, 'Bloody Whirlwind', 0, 1, 0),
(950021, 900117, 'Speedy Bloodthirst', 0, 1, 0),
(950022, 900118, 'Whirlwind: Overpower', 0, 1, 0),
(950023, 900119, 'Whirlwind: Bloodthirst', 0, 1, 0),
(950024, 900168, 'Revenge: +50% Damage', 0, 1, 0),
(950025, 900169, 'Revenge: Sweeping', 0, 1, 0),
(950026, 900170, 'Thunder Clap: Rend and Sunder', 0, 1, 0),
(950027, 900171, 'Thunder Clap: +50% Damage', 0, 1, 0),
(950028, 900172, 'Devastate Lightning', 0, 1, 0),
(950029, 900173, 'Block: Enhanced Thunder Clap', 0, 1, 0),
(950030, 900200, 'Holy Shock: Burst', 0, 1, 0),
(950031, 900201, 'Holy Shock: Radiance', 0, 1, 0),
(950032, 900202, 'Holy Shock: Both Ways', 0, 1, 0),
(950033, 900203, 'Holy Shock: +50% Effect', 0, 1, 0),
(950034, 900204, 'Consecration: Healing', 0, 1, 0),
(950035, 900205, 'Consecration: Follows You', 0, 1, 0),
(950036, 900206, 'Consecration: +50% Damage', 0, 1, 0),
(950037, 900207, 'Consecration: +5 sec Duration', 0, 1, 0),
(950038, 900234, 'Consecration: Follows You', 0, 1, 0),
(950039, 900235, 'Avenger''s Shield: +9 Targets', 0, 1, 0),
(950040, 900236, 'Avenger''s Shield: +50% Damage', 0, 1, 0),
(950041, 900237, 'Holy Shield: +99 Charges', 0, 1, 0),
(950042, 900238, 'Holy Shield: +50% Damage', 0, 1, 0),
(950043, 900239, 'Avenger''s Shield: Consecration', 0, 1, 0),
(950044, 900240, 'Judgement: Avenger''s Shield', 0, 1, 0),
(950045, 900241, 'Judgement: -2 sec Cooldown', 0, 1, 0),
(950046, 900268, 'Consecration: Follows You', 0, 1, 0),
(950047, 900269, 'Judgement: -2 sec Cooldown', 0, 1, 0),
(950048, 900270, 'Divine Storm: +6 Targets', 0, 1, 0),
(950049, 900271, 'Divine Storm: +50% Damage', 0, 1, 0),
(950050, 900272, 'Crusader Strike: +50% Damage', 0, 1, 0),
(950051, 900273, 'Crusader Strike: +9 Targets', 0, 1, 0),
(950052, 900274, 'Exorcism Power', 0, 1, 0),
(950053, 900500, 'Recovered Arrows', 0, 1, 0),
(950054, 900501, 'Multi-Shot: Unlimited Targets', 0, 1, 0),
(950055, 900502, 'Pet: +50% Damage', 0, 1, 0),
(950056, 900503, 'Pet: +50% Attack Speed', 0, 1, 0),
(950057, 900504, 'Pet: Beast Cleave', 0, 1, 0),
(950058, 900533, 'Auto Shot: Ricochet', 0, 1, 0),
(950059, 900566, 'Explosive Traps', 0, 1, 0),
(950060, 900600, 'Energy: +50% Regeneration', 0, 1, 0),
(950061, 900601, 'Mutilate: +50% Damage', 0, 1, 0),
(950062, 900602, 'Poisons: +50% Damage', 0, 1, 0),
(950063, 900603, 'Poison Nova', 0, 1, 0),
(950064, 900633, 'Sinister Strike: +50% Damage', 0, 1, 0),
(950065, 900634, 'Sinister Strike: +9 Targets', 0, 1, 0),
(950066, 900635, 'Blade Flurry: 2 min Duration', 0, 1, 0),
(950067, 900636, 'Blade Flurry: +9 Targets', 0, 1, 0),
(950068, 900637, 'Energy: +50% Regeneration', 0, 1, 0),
(950069, 900666, 'Energy: +50% Regeneration', 0, 1, 0),
(950070, 900667, 'Hemorrhage: +50% Damage', 0, 1, 0),
(950071, 900668, 'Hemorrhage: +9 Targets', 0, 1, 0),
(950072, 900900, 'Power Word: Shield: Explosion', 0, 1, 0),
(950073, 900901, 'Power Word: Shield: +50% Absorption', 0, 1, 0),
(950074, 900902, 'Weakened Soul: 5 sec', 0, 1, 0),
(950075, 900933, 'Holy Fire Heals', 0, 1, 0),
(950076, 900966, 'Shadow Eruption', 0, 1, 0),
(950077, 900967, 'Spreading Shadows', 0, 1, 0),
(950078, 900300, 'Dancing Rune Weapon: Three Blades', 0, 1, 0),
(950079, 900301, 'Dancing Rune Weapon: Double Cast', 0, 1, 0),
(950080, 900302, 'Heart Strike: +50% Damage', 0, 1, 0),
(950081, 900303, 'Heart Strike: +9 Targets', 0, 1, 0),
(950082, 900304, 'Death Coil Strikes', 0, 1, 0),
(950083, 900333, 'Raise Dead: Frost Wyrm', 0, 1, 0),
(950084, 900366, 'Plague Eruption', 0, 1, 0),
(950085, 900400, 'Chain Lightning: +6 Targets', 0, 1, 0),
(950086, 900401, 'Totems Follow You', 0, 1, 0),
(950087, 900402, 'Fire Elemental: Ragnaros', 0, 1, 0),
(950088, 900403, 'Lava Overload', 0, 1, 0),
(950089, 900404, 'Lava Burst: Spreading Flame', 0, 1, 0),
(950090, 900405, 'Flame Shock: Lava Reset', 0, 1, 0),
(950091, 900406, 'Lava Burst: Two Charges', 0, 1, 0),
(950092, 900407, 'Lava Burst: Clearcast Instant', 0, 1, 0),
(950093, 900433, 'Totems Follow You', 0, 1, 0),
(950094, 900434, 'Maelstrom Fury', 0, 1, 0),
(950095, 900435, 'Empowered Summons', 0, 1, 0),
(950096, 900436, 'Spirit Wolf Call', 0, 1, 0),
(950097, 900437, 'Spirit Wolves: Haste', 0, 1, 0),
(950098, 900438, 'Spirit Wolves: Chain Lightning', 0, 1, 0),
(950099, 900466, 'Totems Follow You', 0, 1, 0),
(950100, 900467, 'Deep Reserves', 0, 1, 0),
(950101, 900700, 'Deep Reserves', 0, 1, 0),
(950102, 900701, 'Arcane Barrage: +50% Damage', 0, 1, 0),
(950103, 900702, 'Arcane Barrage: +9 Targets', 0, 1, 0),
(950104, 900703, 'Arcane Blast: -50% Cast Time', 0, 1, 0),
(950105, 900704, 'Arcane Blast: +9 Targets', 0, 1, 0),
(950106, 900705, 'Arcane Blast: 8 Charges', 0, 1, 0),
(950107, 900706, 'Arcane Explosion: Charges', 0, 1, 0),
(950108, 900707, 'Evocation Power', 0, 1, 0),
(950109, 900708, 'Emergency Mana Shield', 0, 1, 0),
(950110, 900709, 'Blink: To Your Target', 0, 1, 0),
(950111, 900733, 'Fireball: +50% Damage', 0, 1, 0),
(950112, 900734, 'Fireball: +9 Targets', 0, 1, 0),
(950113, 900735, 'Pyroblast: +9 Targets', 0, 1, 0),
(950114, 900736, 'Pyroblast: +50% Damage', 0, 1, 0),
(950115, 900737, 'Fire Blast: Swift and Sure', 0, 1, 0),
(950116, 900738, 'Pyroblast: Hot Streak', 0, 1, 0),
(950117, 900766, 'Frostbolt: +50% Damage', 0, 1, 0),
(950118, 900767, 'Frostbolt: +9 Targets', 0, 1, 0),
(950119, 900768, 'Ice Lance: +50% Damage', 0, 1, 0),
(950120, 900769, 'Ice Lance: +9 Targets', 0, 1, 0),
(950121, 900770, 'Water Elemental: Permanent', 0, 1, 0),
(950122, 900800, 'Shadow Eruption', 0, 1, 0),
(950123, 900801, 'Corruption: +50% Damage', 0, 1, 0),
(950124, 900802, 'Spreading Affliction', 0, 1, 0),
(950125, 900833, 'Metamorphosis: Feast', 0, 1, 0),
(950126, 900834, 'Metamorphosis: Fel Vigor', 0, 1, 0),
(950127, 900835, 'Lesser Demons', 0, 1, 0),
(950128, 900836, 'Imp: +50% Damage', 0, 1, 0),
(950129, 900837, 'Imp: Firebolt +9 Targets', 0, 1, 0),
(950130, 900838, 'Felguard: Unlimited Cleave', 0, 1, 0),
(950131, 900839, 'Felguard: +50% Damage', 0, 1, 0),
(950132, 900866, 'Shadow Bolt: +9 Targets', 0, 1, 0),
(950133, 900867, 'Shadow Bolt: +50% Damage', 0, 1, 0),
(950134, 900868, 'Chaos Bolt: +50% Damage', 0, 1, 0),
(950135, 900869, 'Chaos Bolt: -2 sec Cooldown', 0, 1, 0),
(950136, 900870, 'Chaos Bolt: +9 Targets', 0, 1, 0),
(950137, 901000, 'Moonfire: +9 Targets', 0, 1, 0),
(950138, 901001, 'Moonfire: +50% Damage', 0, 1, 0),
(950139, 901002, 'Starfall: +50% Area', 0, 1, 0),
(950140, 901003, 'Starfall: +50% Damage', 0, 1, 0),
(950141, 901004, 'Starfall: Starlight Reset', 0, 1, 0),
(950142, 901005, 'Starfall: 10 Stacks', 0, 1, 0),
(950143, 901033, 'Swipe (Bear): Bleed', 0, 1, 0),
(950144, 901049, 'Swipe (Cat): Bleed', 0, 1, 0),
(950145, 901051, 'Energy: +50% Regeneration', 0, 1, 0),
(950146, 901066, 'Treant Call', 0, 1, 0),
(950147, 901067, 'Summons: Healing Power', 0, 1, 0),
(950148, 901068, 'Summons: Parting Bloom', 0, 1, 0),
(950149, 901069, 'Thorns: Rejuvenation', 0, 1, 0),
(950150, 901070, 'Heal over Time: +50%', 0, 1, 0),
(950151, 901071, 'Heal over Time: Double Speed', 0, 1, 0),
(950152, 901072, 'Deep Reserves', 0, 1, 0),
(950153, 901101, 'Killing Blow: Recovery', 0, 1, 0),
(950154, 901102, 'Extra Attack', 0, 1, 0),
(950155, 901103, 'Cleaving Strikes', 0, 1, 0),
(950156, 901104, 'Riposte', 0, 1, 0),
(950157, 900133, 'Whirlwind: Any Stance', 0, 1, 0),
(950158, 901111, 'Empowered', 0, 1, 0),
(950159, 900306, 'Bloodworm Burst', 0, 1, 0),
(950160, 900334, 'Obliterate: +50% Damage', 0, 1, 0),
(950161, 900335, 'Obliterate: +9 Targets', 0, 1, 0),
(950162, 900336, 'Howling Blast: +50% Damage', 0, 1, 0),
(950163, 900337, 'Howling Blast: Frost Fever', 0, 1, 0),
(950164, 900338, 'Lichborne: Leech', 0, 1, 0),
(950165, 900340, 'Icy Talons: Frozen Strikes', 0, 1, 0),
(950166, 900369, 'Ghoul Cleave', 0, 1, 0),
(950167, 900371, 'Risen Army', 0, 1, 0),
(950168, 900373, 'Death and Decay: Around You', 0, 1, 0),
(950169, 900410, 'Lightning Bolt: +50% Damage', 0, 1, 0),
(950170, 900411, 'Lightning Bolt: +9 Targets', 0, 1, 0),
(950171, 900412, 'Chain Lightning: +50% Damage', 0, 1, 0),
(950172, 900413, 'Lava Burst: +50% Damage', 0, 1, 0),
(950173, 900414, 'Lava Burst: +9 Targets', 0, 1, 0),
(950174, 900415, 'Elemental Resonance', 0, 1, 0),
(950175, 900418, 'Lightning Shield: Chain Lightning', 0, 1, 0),
(950176, 900714, 'Arcane Overflow', 0, 1, 0),
(950177, 900715, 'Mirror Shield', 0, 1, 0),
(950178, 900716, 'Mirror Images: Splash', 0, 1, 0),
(950179, 901035, 'Maul: Bleeding Wounds', 0, 1, 0),
(950180, 900507, 'Pet: +100% Health', 0, 1, 0),
(950181, 900525, 'Second Pet', 0, 1, 0),
(950182, 900537, 'Multi-Shot: Serpent Sting', 0, 1, 0),
(950183, 900538, 'Chimera Shot: +9 Targets', 0, 1, 0),
(950184, 900539, 'Chimera Shot: +50% Damage', 0, 1, 0),
(950185, 900540, 'Running Aim', 0, 1, 0),
(950186, 900568, 'Blade and Shot', 0, 1, 0),
(950187, 900571, 'Raptor Strike: +9 Targets', 0, 1, 0),
(950188, 900572, 'Raptor Strike: +50% Damage', 0, 1, 0),
(950189, 900605, 'Mutilate: +9 Targets', 0, 1, 0),
(950190, 900639, 'Adrenaline Rush: Unleashed', 0, 1, 0),
(950191, 900642, 'Killing Spree: Fan of Knives', 0, 1, 0),
(950192, 900670, 'Ambush: +9 Targets', 0, 1, 0),
(950193, 900671, 'Ambush: +50% Damage', 0, 1, 0),
(950194, 900672, 'Shadow Dance: Flow', 0, 1, 0),
(950195, 900674, 'Frontal Assault', 0, 1, 0),
(950196, 900904, 'Atonement', 0, 1, 0),
(950197, 900905, 'Smite: +9 Targets', 0, 1, 0),
(950198, 900906, 'Smite: +50% Damage', 0, 1, 0),
(950199, 900935, 'Holy Fire: +9 Targets', 0, 1, 0),
(950200, 900936, 'Holy Fire: +50% Damage', 0, 1, 0),
(950201, 900937, 'Lightwell: Auto Renew', 0, 1, 0),
(950202, 900938, 'Spirit of Redemption: Guardian', 0, 1, 0),
(950203, 900941, 'Holy Nova: +50% Radius', 0, 1, 0),
(950204, 900942, 'Holy Nova: Kindled Fire', 0, 1, 0),
(950205, 900969, 'Shadow Word: Pain: +50% Damage', 0, 1, 0),
(950206, 900970, 'Mind Blast: +50% Damage', 0, 1, 0),
(950207, 900971, 'Mind Blast: +9 Targets', 0, 1, 0),
(950208, 900972, 'Shadowform: Soul Feast', 0, 1, 0),
(950209, 900975, 'Shadowform: Lesser Tentacles', 0, 1, 0),
(950210, 900804, 'Withering Harvest', 0, 1, 0),
(950211, 900846, 'Imp: Firebolt 50% Faster', 0, 1, 0),
(950212, 900848, 'Voidwalker: Void Bulwark', 0, 1, 0),
(950213, 900850, 'Succubus: Mass Seduction', 0, 1, 0),
(950214, 900852, 'Felhunter: Area Spell Lock and Devour Magic', 0, 1, 0),
(950215, 900858, 'Second Demon', 0, 1, 0),
(950216, 900873, 'Hellfire: Free Movement', 0, 1, 0),
(950217, 900875, 'Rain of Fire: Around You', 0, 1, 0),
(950218, 901006, 'Lunar Frenzy', 0, 1, 0),
(950219, 901036, 'Swipe (Bear): +50% Damage', 0, 1, 0),
(950220, 901037, 'Thorns: Open Wounds', 0, 1, 0),
(950221, 901039, 'Ursine Bulwark', 0, 1, 0),
(950222, 901052, 'Swipe (Cat): +50% Damage', 0, 1, 0),
(950223, 901053, 'Frontal Assault', 0, 1, 0),
(950224, 901054, 'Berserk: Unleashed', 0, 1, 0);

DELETE FROM `paragon_spec_spell_assign` WHERE `enchantmentId` BETWEEN 950007 AND 950224;
INSERT INTO `paragon_spec_spell_assign` (`specId`, `enchantmentId`, `weight`) VALUES
-- 900100 Mortal Strike: +50% Damage (Warrior Arms -> Arms)
(1, 950007, 10),
-- 900101 Mortal Strike: -2 sec Cooldown (Warrior Arms -> Arms)
(1, 950008, 10),
-- 900102 Overpower: +50% Damage (Warrior Arms -> Arms)
(1, 950009, 10),
-- 900103 Mortal Strike: +9 Targets (Warrior Arms -> Arms)
(1, 950010, 10),
-- 900104 Overpower: +9 Targets (Warrior Arms -> Arms)
(1, 950011, 10),
-- 900105 Critical Execution (Warrior Arms -> Arms)
(1, 950012, 10),
-- 900107 Timed Attacks (Warrior Arms -> Arms)
(1, 950013, 10),
-- 900108 Whirlwind: Unlimited Targets (Warrior Fury -> Arms, Fury)
(1, 950014, 10), (2, 950014, 10),
-- 900109 Bloodthirst: +50% Damage (Warrior Fury -> Fury)
(2, 950015, 10),
-- 900110 Bloodthirst: +9 Targets (Warrior Fury -> Fury)
(2, 950016, 10),
-- 900111 Whirlwind: +50% Damage (Warrior Fury -> Fury)
(2, 950017, 10),
-- 900112 Cleave: Unlimited Targets (Warrior Fury -> Fury)
(2, 950018, 10),
-- 900114 Whirly Attacks (Warrior Fury -> Fury)
(2, 950019, 10),
-- 900116 Bloody Whirlwind (Warrior Fury -> Fury)
(2, 950020, 10),
-- 900117 Speedy Bloodthirst (Warrior Fury -> Fury)
(2, 950021, 10),
-- 900118 Whirlwind: Overpower (Warrior Arms -> Arms)
(1, 950022, 10),
-- 900119 Whirlwind: Bloodthirst (Warrior Fury -> Fury)
(2, 950023, 10),
-- 900168 Revenge: +50% Damage (Warrior Protection -> WarProt)
(3, 950024, 10),
-- 900169 Revenge: Sweeping (Warrior Protection -> WarProt)
(3, 950025, 10),
-- 900170 Thunder Clap: Rend and Sunder (Warrior Protection -> Arms, WarProt)
(1, 950026, 10), (3, 950026, 10),
-- 900171 Thunder Clap: +50% Damage (Warrior Protection -> WarProt)
(3, 950027, 10),
-- 900172 Devastate Lightning (Warrior Protection -> WarProt)
(3, 950028, 10),
-- 900173 Block: Enhanced Thunder Clap (Warrior Protection -> WarProt)
(3, 950029, 10),
-- 900200 Holy Shock: Burst (Paladin Holy -> HolyPala)
(4, 950030, 10),
-- 900201 Holy Shock: Radiance (Paladin Holy -> HolyPala)
(4, 950031, 10),
-- 900202 Holy Shock: Both Ways (Paladin Holy -> HolyPala)
(4, 950032, 10),
-- 900203 Holy Shock: +50% Effect (Paladin Holy -> HolyPala)
(4, 950033, 10),
-- 900204 Consecration: Healing (Paladin Holy -> HolyPala)
(4, 950034, 10),
-- 900205 Consecration: Follows You (Paladin Holy -> HolyPala)
(4, 950035, 10),
-- 900206 Consecration: +50% Damage (Paladin Holy -> HolyPala)
(4, 950036, 10),
-- 900207 Consecration: +5 sec Duration (Paladin Holy -> HolyPala)
(4, 950037, 10),
-- 900234 Consecration: Follows You (Paladin Protection -> ProtPala)
(5, 950038, 10),
-- 900235 Avenger's Shield: +9 Targets (Paladin Protection -> ProtPala)
(5, 950039, 10),
-- 900236 Avenger's Shield: +50% Damage (Paladin Protection -> ProtPala)
(5, 950040, 10),
-- 900237 Holy Shield: +99 Charges (Paladin Protection -> ProtPala)
(5, 950041, 10),
-- 900238 Holy Shield: +50% Damage (Paladin Protection -> ProtPala)
(5, 950042, 10),
-- 900239 Avenger's Shield: Consecration (Paladin Protection -> ProtPala)
(5, 950043, 10),
-- 900240 Judgement: Avenger's Shield (Paladin Protection -> ProtPala)
(5, 950044, 10),
-- 900241 Judgement: -2 sec Cooldown (Paladin Protection -> ProtPala)
(5, 950045, 10),
-- 900268 Consecration: Follows You (Paladin Retribution -> Ret)
(6, 950046, 10),
-- 900269 Judgement: -2 sec Cooldown (Paladin Retribution -> Ret)
(6, 950047, 10),
-- 900270 Divine Storm: +6 Targets (Paladin Retribution -> Ret)
(6, 950048, 10),
-- 900271 Divine Storm: +50% Damage (Paladin Retribution -> Ret)
(6, 950049, 10),
-- 900272 Crusader Strike: +50% Damage (Paladin Retribution -> Ret)
(6, 950050, 10),
-- 900273 Crusader Strike: +9 Targets (Paladin Retribution -> Ret)
(6, 950051, 10),
-- 900274 Exorcism Power (Paladin Retribution -> Ret)
(6, 950052, 10),
-- 900500 Recovered Arrows (Hunter Shared -> BM, MM, Surv)
(13, 950053, 10), (14, 950053, 10), (15, 950053, 10),
-- 900501 Multi-Shot: Unlimited Targets (Hunter Shared -> BM, MM, Surv)
(13, 950054, 10), (14, 950054, 10), (15, 950054, 10),
-- 900502 Pet: +50% Damage (Hunter Beast Mastery -> BM)
(13, 950055, 10),
-- 900503 Pet: +50% Attack Speed (Hunter Beast Mastery -> BM)
(13, 950056, 10),
-- 900504 Pet: Beast Cleave (Hunter Beast Mastery -> BM)
(13, 950057, 10),
-- 900533 Auto Shot: Ricochet (Hunter Marksmanship -> MM)
(14, 950058, 10),
-- 900566 Explosive Traps (Hunter Survival -> Surv)
(15, 950059, 10),
-- 900600 Energy: +50% Regeneration (Rogue Assassination -> Assa)
(20, 950060, 10),
-- 900601 Mutilate: +50% Damage (Rogue Assassination -> Assa)
(20, 950061, 10),
-- 900602 Poisons: +50% Damage (Rogue Assassination -> Assa)
(20, 950062, 10),
-- 900603 Poison Nova (Rogue Assassination -> Assa)
(20, 950063, 10),
-- 900633 Sinister Strike: +50% Damage (Rogue Combat -> Combat)
(21, 950064, 10),
-- 900634 Sinister Strike: +9 Targets (Rogue Combat -> Combat)
(21, 950065, 10),
-- 900635 Blade Flurry: 2 min Duration (Rogue Combat -> Combat)
(21, 950066, 10),
-- 900636 Blade Flurry: +9 Targets (Rogue Combat -> Combat)
(21, 950067, 10),
-- 900637 Energy: +50% Regeneration (Rogue Combat -> Combat)
(21, 950068, 10),
-- 900666 Energy: +50% Regeneration (Rogue Subtlety -> Sub)
(22, 950069, 10),
-- 900667 Hemorrhage: +50% Damage (Rogue Subtlety -> Sub)
(22, 950070, 10),
-- 900668 Hemorrhage: +9 Targets (Rogue Subtlety -> Sub)
(22, 950071, 10),
-- 900900 Power Word: Shield: Explosion (Priest Discipline -> Disc)
(29, 950072, 10),
-- 900901 Power Word: Shield: +50% Absorption (Priest Discipline -> Disc)
(29, 950073, 10),
-- 900902 Weakened Soul: 5 sec (Priest Discipline -> Disc)
(29, 950074, 10),
-- 900933 Holy Fire Heals (Priest Holy -> HolyPri)
(30, 950075, 10),
-- 900966 Shadow Eruption (Priest Shadow -> Shadow)
(31, 950076, 10),
-- 900967 Spreading Shadows (Priest Shadow -> Shadow)
(31, 950077, 10),
-- 900300 Dancing Rune Weapon: Three Blades (Death Knight Blood -> Blood)
(7, 950078, 10),
-- 900301 Dancing Rune Weapon: Double Cast (Death Knight Blood -> Blood)
(7, 950079, 10),
-- 900302 Heart Strike: +50% Damage (Death Knight Blood -> Blood)
(7, 950080, 10),
-- 900303 Heart Strike: +9 Targets (Death Knight Blood -> Blood)
(7, 950081, 10),
-- 900304 Death Coil Strikes (Death Knight Blood -> Blood)
(7, 950082, 10),
-- 900333 Raise Dead: Frost Wyrm (Death Knight Frost -> DKFrost)
(8, 950083, 10),
-- 900366 Plague Eruption (Death Knight Unholy -> Unholy)
(9, 950084, 10),
-- 900400 Chain Lightning: +6 Targets (Shaman Elemental -> Ele)
(10, 950085, 10),
-- 900401 Totems Follow You (Shaman Elemental -> Ele)
(10, 950086, 10),
-- 900402 Fire Elemental: Ragnaros (Shaman Elemental -> Ele)
(10, 950087, 10),
-- 900403 Lava Overload (Shaman Elemental -> Ele)
(10, 950088, 10),
-- 900404 Lava Burst: Spreading Flame (Shaman Elemental -> Ele)
(10, 950089, 10),
-- 900405 Flame Shock: Lava Reset (Shaman Elemental -> Ele)
(10, 950090, 10),
-- 900406 Lava Burst: Two Charges (Shaman Elemental -> Ele)
(10, 950091, 10),
-- 900407 Lava Burst: Clearcast Instant (Shaman Elemental -> Ele)
(10, 950092, 10),
-- 900433 Totems Follow You (Shaman Enhancement -> Enhance)
(11, 950093, 10),
-- 900434 Maelstrom Fury (Shaman Enhancement -> Enhance)
(11, 950094, 10),
-- 900435 Empowered Summons (Shaman Enhancement -> Enhance)
(11, 950095, 10),
-- 900436 Spirit Wolf Call (Shaman Enhancement -> Enhance)
(11, 950096, 10),
-- 900437 Spirit Wolves: Haste (Shaman Enhancement -> Enhance)
(11, 950097, 10),
-- 900438 Spirit Wolves: Chain Lightning (Shaman Enhancement -> Enhance)
(11, 950098, 10),
-- 900466 Totems Follow You (Shaman Restoration -> RestoSham)
(12, 950099, 10),
-- 900467 Deep Reserves (Shaman Restoration -> RestoSham)
(12, 950100, 10),
-- 900700 Deep Reserves (Mage Arcane -> Arcane)
(23, 950101, 10),
-- 900701 Arcane Barrage: +50% Damage (Mage Arcane -> Arcane)
(23, 950102, 10),
-- 900702 Arcane Barrage: +9 Targets (Mage Arcane -> Arcane)
(23, 950103, 10),
-- 900703 Arcane Blast: -50% Cast Time (Mage Arcane -> Arcane)
(23, 950104, 10),
-- 900704 Arcane Blast: +9 Targets (Mage Arcane -> Arcane)
(23, 950105, 10),
-- 900705 Arcane Blast: 8 Charges (Mage Arcane -> Arcane)
(23, 950106, 10),
-- 900706 Arcane Explosion: Charges (Mage Arcane -> Arcane)
(23, 950107, 10),
-- 900707 Evocation Power (Mage Arcane -> Arcane, Fire, MageFrost)
(23, 950108, 10), (24, 950108, 10), (25, 950108, 10),
-- 900708 Emergency Mana Shield (Mage Arcane -> Arcane)
(23, 950109, 10),
-- 900709 Blink: To Your Target (Mage Arcane -> Arcane)
(23, 950110, 10),
-- 900733 Fireball: +50% Damage (Mage Fire -> Fire)
(24, 950111, 10),
-- 900734 Fireball: +9 Targets (Mage Fire -> Fire)
(24, 950112, 10),
-- 900735 Pyroblast: +9 Targets (Mage Fire -> Fire)
(24, 950113, 10),
-- 900736 Pyroblast: +50% Damage (Mage Fire -> Fire)
(24, 950114, 10),
-- 900737 Fire Blast: Swift and Sure (Mage Fire -> Fire)
(24, 950115, 10),
-- 900738 Pyroblast: Hot Streak (Mage Fire -> Fire)
(24, 950116, 10),
-- 900766 Frostbolt: +50% Damage (Mage Frost -> MageFrost)
(25, 950117, 10),
-- 900767 Frostbolt: +9 Targets (Mage Frost -> MageFrost)
(25, 950118, 10),
-- 900768 Ice Lance: +50% Damage (Mage Frost -> MageFrost)
(25, 950119, 10),
-- 900769 Ice Lance: +9 Targets (Mage Frost -> MageFrost)
(25, 950120, 10),
-- 900770 Water Elemental: Permanent (Mage Frost -> MageFrost)
(25, 950121, 10),
-- 900800 Shadow Eruption (Warlock Affliction -> Affli)
(26, 950122, 10),
-- 900801 Corruption: +50% Damage (Warlock Affliction -> Affli)
(26, 950123, 10),
-- 900802 Spreading Affliction (Warlock Affliction -> Affli)
(26, 950124, 10),
-- 900833 Metamorphosis: Feast (Warlock Demonology -> Demo)
(27, 950125, 10),
-- 900834 Metamorphosis: Fel Vigor (Warlock Demonology -> Demo)
(27, 950126, 10),
-- 900835 Lesser Demons (Warlock Demonology -> Demo)
(27, 950127, 10),
-- 900836 Imp: +50% Damage (Warlock Demonology -> Demo)
(27, 950128, 10),
-- 900837 Imp: Firebolt +9 Targets (Warlock Demonology -> Demo)
(27, 950129, 10),
-- 900838 Felguard: Unlimited Cleave (Warlock Demonology -> Demo)
(27, 950130, 10),
-- 900839 Felguard: +50% Damage (Warlock Demonology -> Demo)
(27, 950131, 10),
-- 900866 Shadow Bolt: +9 Targets (Warlock Destruction -> Destro)
(28, 950132, 10),
-- 900867 Shadow Bolt: +50% Damage (Warlock Destruction -> Destro)
(28, 950133, 10),
-- 900868 Chaos Bolt: +50% Damage (Warlock Destruction -> Destro)
(28, 950134, 10),
-- 900869 Chaos Bolt: -2 sec Cooldown (Warlock Destruction -> Destro)
(28, 950135, 10),
-- 900870 Chaos Bolt: +9 Targets (Warlock Destruction -> Destro)
(28, 950136, 10),
-- 901000 Moonfire: +9 Targets (Druid Balance -> Balance)
(16, 950137, 10),
-- 901001 Moonfire: +50% Damage (Druid Balance -> Balance)
(16, 950138, 10),
-- 901002 Starfall: +50% Area (Druid Balance -> Balance)
(16, 950139, 10),
-- 901003 Starfall: +50% Damage (Druid Balance -> Balance)
(16, 950140, 10),
-- 901004 Starfall: Starlight Reset (Druid Balance -> Balance)
(16, 950141, 10),
-- 901005 Starfall: 10 Stacks (Druid Balance -> Balance)
(16, 950142, 10),
-- 901033 Swipe (Bear): Bleed (Druid Feral -> FeralTank)
(18, 950143, 10),
-- 901049 Swipe (Cat): Bleed (Druid Feral -> FeralDPS)
(19, 950144, 10),
-- 901051 Energy: +50% Regeneration (Druid Feral -> FeralDPS)
(19, 950145, 10),
-- 901066 Treant Call (Druid Restoration -> RestoDru)
(17, 950146, 10),
-- 901067 Summons: Healing Power (Druid Restoration -> RestoDru)
(17, 950147, 10),
-- 901068 Summons: Parting Bloom (Druid Restoration -> RestoDru)
(17, 950148, 10),
-- 901069 Thorns: Rejuvenation (Druid Restoration -> RestoDru)
(17, 950149, 10),
-- 901070 Heal over Time: +50% (Druid Restoration -> RestoDru)
(17, 950150, 10),
-- 901071 Heal over Time: Double Speed (Druid Restoration -> RestoDru)
(17, 950151, 10),
-- 901072 Deep Reserves (Druid Restoration -> RestoDru)
(17, 950152, 10),
-- 901101 Killing Blow: Recovery (Global Global -> Arms, Fury, WarProt, HolyPala, ProtPala, Ret, Blood, DKFrost, Unholy, Ele, Enhance, RestoSham, BM, MM, Surv, Balance, RestoDru, FeralTank, FeralDPS, Assa, Combat, Sub, Arcane, Fire, MageFrost, Affli, Demo, Destro, Disc, HolyPri, Shadow)
(1, 950153, 10), (2, 950153, 10), (3, 950153, 10), (4, 950153, 10), (5, 950153, 10), (6, 950153, 10), (7, 950153, 10), (8, 950153, 10), (9, 950153, 10), (10, 950153, 10), (11, 950153, 10), (12, 950153, 10), (13, 950153, 10), (14, 950153, 10), (15, 950153, 10), (16, 950153, 10), (17, 950153, 10), (18, 950153, 10), (19, 950153, 10), (20, 950153, 10), (21, 950153, 10), (22, 950153, 10), (23, 950153, 10), (24, 950153, 10), (25, 950153, 10), (26, 950153, 10), (27, 950153, 10), (28, 950153, 10), (29, 950153, 10), (30, 950153, 10), (31, 950153, 10),
-- 901102 Extra Attack (Global Global -> Arms, Fury, WarProt, HolyPala, ProtPala, Ret, Blood, DKFrost, Unholy, Ele, Enhance, RestoSham, BM, MM, Surv, Balance, RestoDru, FeralTank, FeralDPS, Assa, Combat, Sub, Arcane, Fire, MageFrost, Affli, Demo, Destro, Disc, HolyPri, Shadow)
(1, 950154, 10), (2, 950154, 10), (3, 950154, 10), (4, 950154, 10), (5, 950154, 10), (6, 950154, 10), (7, 950154, 10), (8, 950154, 10), (9, 950154, 10), (10, 950154, 10), (11, 950154, 10), (12, 950154, 10), (13, 950154, 10), (14, 950154, 10), (15, 950154, 10), (16, 950154, 10), (17, 950154, 10), (18, 950154, 10), (19, 950154, 10), (20, 950154, 10), (21, 950154, 10), (22, 950154, 10), (23, 950154, 10), (24, 950154, 10), (25, 950154, 10), (26, 950154, 10), (27, 950154, 10), (28, 950154, 10), (29, 950154, 10), (30, 950154, 10), (31, 950154, 10),
-- 901103 Cleaving Strikes (Global Global -> Arms, Fury, WarProt, HolyPala, ProtPala, Ret, Blood, DKFrost, Unholy, Ele, Enhance, RestoSham, BM, MM, Surv, Balance, RestoDru, FeralTank, FeralDPS, Assa, Combat, Sub, Arcane, Fire, MageFrost, Affli, Demo, Destro, Disc, HolyPri, Shadow)
(1, 950155, 10), (2, 950155, 10), (3, 950155, 10), (4, 950155, 10), (5, 950155, 10), (6, 950155, 10), (7, 950155, 10), (8, 950155, 10), (9, 950155, 10), (10, 950155, 10), (11, 950155, 10), (12, 950155, 10), (13, 950155, 10), (14, 950155, 10), (15, 950155, 10), (16, 950155, 10), (17, 950155, 10), (18, 950155, 10), (19, 950155, 10), (20, 950155, 10), (21, 950155, 10), (22, 950155, 10), (23, 950155, 10), (24, 950155, 10), (25, 950155, 10), (26, 950155, 10), (27, 950155, 10), (28, 950155, 10), (29, 950155, 10), (30, 950155, 10), (31, 950155, 10),
-- 901104 Riposte (Global Global -> Arms, Fury, WarProt, HolyPala, ProtPala, Ret, Blood, DKFrost, Unholy, Ele, Enhance, RestoSham, BM, MM, Surv, Balance, RestoDru, FeralTank, FeralDPS, Assa, Combat, Sub, Arcane, Fire, MageFrost, Affli, Demo, Destro, Disc, HolyPri, Shadow)
(1, 950156, 10), (2, 950156, 10), (3, 950156, 10), (4, 950156, 10), (5, 950156, 10), (6, 950156, 10), (7, 950156, 10), (8, 950156, 10), (9, 950156, 10), (10, 950156, 10), (11, 950156, 10), (12, 950156, 10), (13, 950156, 10), (14, 950156, 10), (15, 950156, 10), (16, 950156, 10), (17, 950156, 10), (18, 950156, 10), (19, 950156, 10), (20, 950156, 10), (21, 950156, 10), (22, 950156, 10), (23, 950156, 10), (24, 950156, 10), (25, 950156, 10), (26, 950156, 10), (27, 950156, 10), (28, 950156, 10), (29, 950156, 10), (30, 950156, 10), (31, 950156, 10),
-- 900133 Whirlwind: Any Stance (Warrior Fury -> Fury)
(2, 950157, 10),
-- 901111 Empowered (Global Global -> Arms, Fury, WarProt, HolyPala, ProtPala, Ret, Blood, DKFrost, Unholy, Ele, Enhance, RestoSham, BM, MM, Surv, Balance, RestoDru, FeralTank, FeralDPS, Assa, Combat, Sub, Arcane, Fire, MageFrost, Affli, Demo, Destro, Disc, HolyPri, Shadow)
(1, 950158, 10), (2, 950158, 10), (3, 950158, 10), (4, 950158, 10), (5, 950158, 10), (6, 950158, 10), (7, 950158, 10), (8, 950158, 10), (9, 950158, 10), (10, 950158, 10), (11, 950158, 10), (12, 950158, 10), (13, 950158, 10), (14, 950158, 10), (15, 950158, 10), (16, 950158, 10), (17, 950158, 10), (18, 950158, 10), (19, 950158, 10), (20, 950158, 10), (21, 950158, 10), (22, 950158, 10), (23, 950158, 10), (24, 950158, 10), (25, 950158, 10), (26, 950158, 10), (27, 950158, 10), (28, 950158, 10), (29, 950158, 10), (30, 950158, 10), (31, 950158, 10),
-- 900306 Bloodworm Burst (Death Knight Blood -> Blood)
(7, 950159, 10),
-- 900334 Obliterate: +50% Damage (Death Knight Frost -> DKFrost)
(8, 950160, 10),
-- 900335 Obliterate: +9 Targets (Death Knight Frost -> DKFrost)
(8, 950161, 10),
-- 900336 Howling Blast: +50% Damage (Death Knight Frost -> DKFrost)
(8, 950162, 10),
-- 900337 Howling Blast: Frost Fever (Death Knight Frost -> DKFrost)
(8, 950163, 10),
-- 900338 Lichborne: Leech (Death Knight Frost -> DKFrost)
(8, 950164, 10),
-- 900340 Icy Talons: Frozen Strikes (Death Knight Frost -> DKFrost)
(8, 950165, 10),
-- 900369 Ghoul Cleave (Death Knight Unholy -> Unholy)
(9, 950166, 10),
-- 900371 Risen Army (Death Knight Unholy -> Unholy)
(9, 950167, 10),
-- 900373 Death and Decay: Around You (Death Knight Unholy -> Unholy)
(9, 950168, 10),
-- 900410 Lightning Bolt: +50% Damage (Shaman Elemental -> Ele)
(10, 950169, 10),
-- 900411 Lightning Bolt: +9 Targets (Shaman Elemental -> Ele)
(10, 950170, 10),
-- 900412 Chain Lightning: +50% Damage (Shaman Elemental -> Ele)
(10, 950171, 10),
-- 900413 Lava Burst: +50% Damage (Shaman Elemental -> Ele)
(10, 950172, 10),
-- 900414 Lava Burst: +9 Targets (Shaman Elemental -> Ele)
(10, 950173, 10),
-- 900415 Elemental Resonance (Shaman Elemental -> Ele)
(10, 950174, 10),
-- 900418 Lightning Shield: Chain Lightning (Shaman Elemental -> Ele)
(10, 950175, 10),
-- 900714 Arcane Overflow (Mage Arcane -> Arcane)
(23, 950176, 10),
-- 900715 Mirror Shield (Mage Arcane -> Arcane)
(23, 950177, 10),
-- 900716 Mirror Images: Splash (Mage Arcane -> Arcane)
(23, 950178, 10),
-- 901035 Maul: Bleeding Wounds (Druid Feral -> FeralTank)
(18, 950179, 10),
-- 900507 Pet: +100% Health (Hunter Beast Mastery -> BM)
(13, 950180, 10),
-- 900525 Second Pet (Hunter Beast Mastery -> BM)
(13, 950181, 10),
-- 900537 Multi-Shot: Serpent Sting (Hunter Marksmanship -> MM)
(14, 950182, 10),
-- 900538 Chimera Shot: +9 Targets (Hunter Marksmanship -> MM)
(14, 950183, 10),
-- 900539 Chimera Shot: +50% Damage (Hunter Marksmanship -> MM)
(14, 950184, 10),
-- 900540 Running Aim (Hunter Marksmanship -> MM)
(14, 950185, 10),
-- 900568 Blade and Shot (Hunter Survival -> Surv)
(15, 950186, 10),
-- 900571 Raptor Strike: +9 Targets (Hunter Survival -> Surv)
(15, 950187, 10),
-- 900572 Raptor Strike: +50% Damage (Hunter Survival -> Surv)
(15, 950188, 10),
-- 900605 Mutilate: +9 Targets (Rogue Assassination -> Assa)
(20, 950189, 10),
-- 900639 Adrenaline Rush: Unleashed (Rogue Combat -> Combat)
(21, 950190, 10),
-- 900642 Killing Spree: Fan of Knives (Rogue Combat -> Combat)
(21, 950191, 10),
-- 900670 Ambush: +9 Targets (Rogue Subtlety -> Sub)
(22, 950192, 10),
-- 900671 Ambush: +50% Damage (Rogue Subtlety -> Sub)
(22, 950193, 10),
-- 900672 Shadow Dance: Flow (Rogue Subtlety -> Sub)
(22, 950194, 10),
-- 900674 Frontal Assault (Rogue Subtlety -> Sub)
(22, 950195, 10),
-- 900904 Atonement (Priest Discipline -> Disc)
(29, 950196, 10),
-- 900905 Smite: +9 Targets (Priest Discipline -> Disc)
(29, 950197, 10),
-- 900906 Smite: +50% Damage (Priest Discipline -> Disc)
(29, 950198, 10),
-- 900935 Holy Fire: +9 Targets (Priest Holy -> HolyPri)
(30, 950199, 10),
-- 900936 Holy Fire: +50% Damage (Priest Holy -> HolyPri)
(30, 950200, 10),
-- 900937 Lightwell: Auto Renew (Priest Holy -> HolyPri)
(30, 950201, 10),
-- 900938 Spirit of Redemption: Guardian (Priest Holy -> HolyPri)
(30, 950202, 10),
-- 900941 Holy Nova: +50% Radius (Priest Holy -> HolyPri)
(30, 950203, 10),
-- 900942 Holy Nova: Kindled Fire (Priest Holy -> HolyPri)
(30, 950204, 10),
-- 900969 Shadow Word: Pain: +50% Damage (Priest Shadow -> Shadow)
(31, 950205, 10),
-- 900970 Mind Blast: +50% Damage (Priest Shadow -> Shadow)
(31, 950206, 10),
-- 900971 Mind Blast: +9 Targets (Priest Shadow -> Shadow)
(31, 950207, 10),
-- 900972 Shadowform: Soul Feast (Priest Shadow -> Shadow)
(31, 950208, 10),
-- 900975 Shadowform: Lesser Tentacles (Priest Shadow -> Shadow)
(31, 950209, 10),
-- 900804 Withering Harvest (Warlock Affliction -> Affli)
(26, 950210, 10),
-- 900846 Imp: Firebolt 50% Faster (Warlock Demonology -> Demo)
(27, 950211, 10),
-- 900848 Voidwalker: Void Bulwark (Warlock Demonology -> Demo)
(27, 950212, 10),
-- 900850 Succubus: Mass Seduction (Warlock Demonology -> Demo)
(27, 950213, 10),
-- 900852 Felhunter: Area Spell Lock and Devour Magic (Warlock Demonology -> Demo)
(27, 950214, 10),
-- 900858 Second Demon (Warlock Demonology -> Demo)
(27, 950215, 10),
-- 900873 Hellfire: Free Movement (Warlock Destruction -> Destro)
(28, 950216, 10),
-- 900875 Rain of Fire: Around You (Warlock Destruction -> Destro)
(28, 950217, 10),
-- 901006 Lunar Frenzy (Druid Balance -> Balance)
(16, 950218, 10),
-- 901036 Swipe (Bear): +50% Damage (Druid Feral -> FeralTank)
(18, 950219, 10),
-- 901037 Thorns: Open Wounds (Druid Feral -> FeralTank)
(18, 950220, 10),
-- 901039 Ursine Bulwark (Druid Feral -> FeralTank)
(18, 950221, 10),
-- 901052 Swipe (Cat): +50% Damage (Druid Feral -> FeralDPS)
(19, 950222, 10),
-- 901053 Frontal Assault (Druid Feral -> FeralDPS)
(19, 950223, 10),
-- 901054 Berserk: Unleashed (Druid Feral -> FeralDPS)
(19, 950224, 10);
